"""Initial

Revision ID: fe9ba1226ef5
Revises:
Create Date: 2024-11-12 16:11:30.316641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9ba1226ef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_skipping', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('initial_date', sa.DateTime(), nullable=False),
    sa.Column('next_date', sa.DateTime(), nullable=False),
    sa.Column('periodicity_years', sa.String(), nullable=True),
    sa.Column('periodicity_months', sa.String(), nullable=True),
    sa.Column('periodicity_weeks', sa.String(), nullable=True),
    sa.Column('periodicity_days', sa.String(), nullable=True),
    sa.Column('periodicity_hours', sa.String(), nullable=True),
    sa.Column('periodicity_minutes', sa.String(), nullable=True),
    sa.Column('periodicity_seconds', sa.String(), nullable=True),
    sa.Column('offset_years', sa.String(), nullable=True),
    sa.Column('offset_months', sa.String(), nullable=True),
    sa.Column('offset_weeks', sa.String(), nullable=True),
    sa.Column('offset_days', sa.String(), nullable=True),
    sa.Column('offset_hours', sa.String(), nullable=True),
    sa.Column('offset_minutes', sa.String(), nullable=True),
    sa.Column('offset_seconds', sa.String(), nullable=True),
    sa.Column('times_occurred', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('entry')
    op.drop_table('occurrence')
    op.drop_table('chat')
    # ### end Alembic commands ###
